language: node_js
os:
 - linux
node_js:
  - "10"
  - "8"
  - "6"
  - "4"
before_install:
  - 'nvm install-latest-npm'
install:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.6" ]; then nvm install --latest-npm 0.8 && npm install && nvm use "${TRAVIS_NODE_VERSION}"; else npm install; fi;'
script:
  - 'if [ -n "${PRETEST-}" ]; then npm run pretest ; fi'
  - 'if [ -n "${POSTTEST-}" ]; then npm run posttest ; fi'
  - 'if [ -n "${COVERAGE-}" ]; then npm run coverage ; fi'
  - 'if [ -n "${REACT-}" ]; then npm run tests-only ; fi'
sudo: false
env:
  - REACT=0.14
  - REACT=15.4
  - REACT=15
  - REACT=16
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: PRETEST=true
    - node_js: "4"
      env: COVERAGE=true
  allow_failures:
    - os: osx
    - env: TEST=true ALLOW_FAILURE=true
